name: Deployment

# on commit push, run job
on: [ push ]

jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    environment: 'iris-prd'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'
    - id: 'tests'
      name: 'Set up Python 3.9'
      uses: 'actions/setup-python@v3'
      with:
        python-version: '3.9'
    - name: 'Install dependencies'
      run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with unittest
      run: |
            export TESTING=True
            python -m unittest
            python ./setup.py sdist --formats=gztar

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'pipeline'
        runtime: 'python39'
        project_id: 'iris-classification-404414'
        region: 'southamerica-east1'
        source_dir: 'src'
        event_trigger_type: 'providers/cloud.pubsub/eventTypes/topic.publish'
        event_trigger_resource: 'projects/iris-classification-404414/topics/run-cloud-function'
        timeout: '539'

    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'dist/iris_trainer-0.1.tar.gz'
        destination: 'iris-classification-bucket/'