name: Deployment

# on commit push, run job
on: [ push ]

jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    environment: 'iris-prd'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        #workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        #service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'pipeline'
        runtime: 'python39'
        project_id: 'iris-classification-404414'
        region: 'southamerica-east1'
        source_dir: 'src'
        event_trigger_type: 'providers/cloud.pubsub/eventTypes/topic.publish'
        event_trigger_resource: 'projects/iris-classification-404414/topics/run-cloud-function'
        timeout: '539'

    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'dist/iris_trainer-0.1.tar.gz'
        destination: 'iris-classification-bucket/'